name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'   # 每天凌晨 2 点自动运行
  workflow_dispatch:       # 手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync upstream changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/fmz200/wool_scripts.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit || true
          git push origin main
